SELECT 
    _FILE,
    _LINE,
    _MODIFIED AS _MODIFIED_TS,
    DATE,
    EXPENSE_TYPE,
    CAST(REPLACE(EXPENSE_AMOUNT, '$', '') AS DECIMAL(10, 2)) AS EXPENSE_AMOUNT_NUMERIC,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS
FROM {{ source('LOAD', 'HR_JOIN') }} 