SELECT _fivetran_id,
CAST(ITEM_NAME AS STRING) AS ITEM_NAME,
ADD_TO_CART_QUANTITY,
REMOVE_FROM_CART_QUANTITY,
PRICE_PER_UNIT,
CAST(SESSION_ID AS STRING) AS SESSION_ID,
ITEM_VIEW_AT AS ITEM_VIEW_AT_TS,
_fivetran_deleted,
_fivetran_synced AS _fivetran_synced_TS
FROM {{SOURCE('snowflake', 'ITEM_VIEWS')}}