SELECT 
    _FILE,
    _LINE,
    _MODIFIED AS _MODIFIED_TS,
    CAST(SUBSTRING(HIRE_DATE FROM 5) AS DATE) AS hiredate_formatted,
    EMPLOYEE_ID,
    NAME,
    ADDRESS,
    CITY,
    TITLE,
    ANNUAL_SALARY,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS
FROM LOAD.GOOGLE_DRIVE.HR_JOIN