select _FIVETRAN_ID,
    SHIPPING_ADDRESS,
    PAYMENT_INFO,
    STATE,
    CAST(SESSION_ID AS STRING) AS SESSION_ID,
    CLIENT_NAME,
    SHIPPING_COST,
    PAYMENT_METHOD,
    TAX_RATE,
    PHONE,
    ORDER_AT AS ORDER_AT_TS,
    ORDER_ID,
    _FIVETRAN_DELETED,
    _FIVETRAN_SYNCED as _FIVETRAN_SYNCED_TS



from {{source('SNOWFLAKE','ORDERS')}}