version: 2

sources:
  - name: snowflake
    database: LOAD  
    schema: SNOWFLAKE_DB_WEB_SCHEMA
    tables:
      - name: ITEM_VIEWS
      - name: ORDERS
      - name: PAGE_VIEWS
      - name: SESSIONS

  - name: google_drive
    database: LOAD  
    schema: GOOGLE_DRIVE
    tables:
      - name: EXPENSES
      - name: RETURNS
      - name: HR_JOINS
      - name: HR_QUITS